environment:
  # Need this to set up compilation on Windows.
  CMD_IN_ENV: cmd /E:ON /V:ON /C Obvious-CI\scripts\obvci_appveyor_python_build_env.cmd
  
  PROJECT_NAME: serpentine
  
  matrix:
    # Unfortunately, compiler/SDK configuration for 64 bit builds depends on
    # python version.
    - TARGET_ARCH: "x64"
      PYTHON_BUILD_RESTRICTIONS: "3.4*"
    - TARGET_ARCH: "x64"
      PYTHON_BUILD_RESTRICTIONS: "3.5*"
    - TARGET_ARCH: "x64"
      PYTHON_BUILD_RESTRICTIONS: "3.6*"

    # For 32 bit builds there are no compiler issues, let Obvious-CI
    # handle the matrix.
    # - TARGET_ARCH: "x86"
    #   PYTHON_BUILD_RESTRICTIONS: "2.7*|>=3.4"

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

install:
    # Clone simply to get the script for setting up Windows build environment.
    - cmd: git clone https://github.com/pelson/Obvious-CI.git
    - cmd: pip install -r requirements.txt

# Skip .NET project specific build phase.
build: off

test_script:
    # Install the package
    - pip install C:\projects\%PROJECT_NAME% pytest
