language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
  - PROJECT_NAME=serpentine
  - GITHUB_REPO_NAME=koszullab/serpentine
os:
- linux
install:
- pip install -r requirements.txt
- pip install pytest pylint pytest-cov pytest-pylint
- python setup.py install
script:
- pytest --pylint --pylint-error-types=EF serpentine
- cd tests;pytest --cov=serpentine
- |
  if [[ $TRAVIS_TAG ]]; then
    python setup.py sdist;
  fi
after_success:
- codecov -e $PYVER
tags: true